services:
  api:
    container_name: crm_api
    image: crm_api
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=CRMSystem;Username=postgres;Password=Emir@123
  db:
    container_name: crm_db
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: Emir@123
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
