services:
  db:
    container_name: crm_db
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: Emir@123
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
